name: Build test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        run: yarn install --frozen-lockfile
      - name: Compile
        run: npm run build
